<?php

namespace Ens\JobeetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class TaskRepository extends EntityRepository
{
  public function getSeachResults($string)
  {
    $qb = $this->createQueryBuilder('t');
 	
 	if($string)
 	{
 		$qb->where('t.name LIKE :string')
 		   ->setParameter('string', '%' . $string . '%');
 	}	
 
    $query = $qb->getQuery();
 
    return $query->getResult();
  }

  public function getTasksByTimestamp($timestamp)
  {
    $qb = $this->createQueryBuilder('t');

 	if($timestamp)
 	{
 		$qb->where('t.due_date <= ?1')
 		   ->setParameter('1', date('Y-m-d H:i:s', $timestamp) );
 	}	

    $query = $qb->getQuery();
 
    return $query->getResult();	

  }
}
