ens_task:
    pattern:  /
    defaults: { _controller: "EnsJobeetBundle:Task:index" }
ens_task_status:
    pattern:  /status/{status}
    defaults: { _controller: "EnsJobeetBundle:Task:index"}
ens_task_time:
    pattern:  /time/{time}
    defaults: { _controller: "EnsJobeetBundle:Task:index"}    
ens_task_search:
    pattern:  /search
    defaults: { _controller: "EnsJobeetBundle:Task:index"}
    requirements: { _method: post }    

ens_task_show:
    pattern:  /{id}/show
    defaults: { _controller: "EnsJobeetBundle:Task:show" }

ens_task_new:
    pattern:  /new
    defaults: { _controller: "EnsJobeetBundle:Task:new" }

ens_task_create:
    pattern:  /create
    defaults: { _controller: "EnsJobeetBundle:Task:create" }
    requirements: { _method: post }

ens_task_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EnsJobeetBundle:Task:edit" }

ens_task_update:
    pattern:  /{id}/update
    defaults: { _controller: "EnsJobeetBundle:Task:update" }
    requirements: { _method: post|put }

ens_task_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EnsJobeetBundle:Task:delete" }
    requirements: { _method: post|delete }
